# Generated by Django 3.2.25 on 2025-06-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20250607_0010'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
